import { useEffect, useState } from 'react'
import type { LayoutManifest } from '../domain/manifest.ts'

// Fetches the layout manifest once at boot. The full manifest (all illustrated
// species) is generated by pipeline/build_masks.py and served from
// /layout-manifest.json. When it is absent — a fresh checkout or a build that
// ships no borrowed art — the hook falls back to a built-in manifest holding
// only the generic silhouette, so every species still packs and renders.

const MANIFEST_URL = '/layout-manifest.json'

/** Fallback-only manifest, baked from pipeline output. The mask is the exact
 *  silhouette of public/assets/illustrations/_fallback.png so packing is
 *  faithful even with no manifest file present. */
export const DEFAULT_MANIFEST: LayoutManifest = {
  dims: { _fallback: [560, 460] },
  masks: {
    _fallback: {
      w: 93,
      h: 76,
      bits: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAAAD//AAAAAAAAAAAAA//+AAAAAAAAAAAAP//4AAAAAAAAAAAD///AAAAAAAAAAAA///8AAAAAAAAAAAP///wAAAAAAAAAAB///+AAAAAAAAAAAP///8AAAAAAAAAwD/j///gAAAAAAAB4f8f///gAAAAAAAH//3////gAAAAAAAP///////AAAAAAAAf//////8AAAAAAAB///////wAAAAAAAD///////gAAAAAAAP//////+AAAAAAAA///////wAAAAAAAH///////AAAAAAAAf//////8AAAAAAAD///////gAAAAAAA///////+AAADAAAH///////wAAH4AAB////////AAP/AAAP///////4Af/wAAB////////B//+AAAP///////////wAAB///////////8AAAP///////////gAAB///////////8AAAP///////////gAAB////////D//4AAAP///////4D//AAAB////////AD/4AAAH///////wAD+AAAA///////+AADwAAAD///////gAAAAAAAf//////8AAAAAAAB///////AAAAAAAAH//////wAAAAAAAAf/////8AAAAAAAAB//////AAAAAAAAAH/////wAAAAAAAAAf////8AAAAAAAAAA////+AAAAAAAAAAB////AAAAAAAAAAAB///gAAAAAAAAAAAB//AAAAAAAAAAAAACAgAAAAAAAAAAAAAQEAAAAAAAAAAAAACAgAAAAAAAAAAAAAQEAAAAAAAAAAAAACAgAAAAAAAAAAAAAQEAAAAAAAAAAAAACAgAAAAAAAAAAAAAQEAAAAAAAAAAAD/////wAAAAAAAAAf/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
    },
  },
  fallbackKey: '_fallback',
}

export interface UseLayoutManifest {
  manifest: LayoutManifest
  loading: boolean
  /** True when the built-in fallback is in use (real manifest unavailable). */
  usingFallback: boolean
}

export function useLayoutManifest(): UseLayoutManifest {
  const [manifest, setManifest] = useState<LayoutManifest>(DEFAULT_MANIFEST)
  const [loading, setLoading] = useState(true)
  const [usingFallback, setUsingFallback] = useState(true)

  useEffect(() => {
    let cancelled = false
    const controller = new AbortController()
    ;(async () => {
      try {
        const res = await fetch(MANIFEST_URL, { signal: controller.signal })
        if (!res.ok) throw new Error(`manifest ${res.status}`)
        const data = (await res.json()) as LayoutManifest
        if (cancelled) return
        if (!data.masks || !data.fallbackKey || !(data.fallbackKey in data.masks)) {
          throw new Error('malformed manifest')
        }
        setManifest(data)
        setUsingFallback(false)
      } catch {
        if (!cancelled) setUsingFallback(true) // keep DEFAULT_MANIFEST
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
      controller.abort()
    }
  }, [])

  return { manifest, loading, usingFallback }
}
